package com.foodenak.itpscanner.persistence.dao;

import android.database.sqlite.SQLiteDatabase;
import com.foodenak.itpscanner.persistence.db.EventEntity;
import com.foodenak.itpscanner.persistence.db.EventImageEntity;
import com.foodenak.itpscanner.persistence.db.HistoryEntity;
import com.foodenak.itpscanner.persistence.db.UserEntity;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

  private final DaoConfig userEntityDaoConfig;
  private final DaoConfig historyEntityDaoConfig;
  private final DaoConfig eventEntityDaoConfig;
  private final DaoConfig eventImageEntityDaoConfig;

  private final UserEntityDao userEntityDao;
  private final HistoryEntityDao historyEntityDao;
  private final EventEntityDao eventEntityDao;
  private final EventImageEntityDao eventImageEntityDao;

  public DaoSession(SQLiteDatabase db, IdentityScopeType type,
      Map<Class<? extends AbstractDao<?, ?>>, DaoConfig> daoConfigMap) {
    super(db);

    userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
    userEntityDaoConfig.initIdentityScope(type);

    historyEntityDaoConfig = daoConfigMap.get(HistoryEntityDao.class).clone();
    historyEntityDaoConfig.initIdentityScope(type);

    eventEntityDaoConfig = daoConfigMap.get(EventEntityDao.class).clone();
    eventEntityDaoConfig.initIdentityScope(type);

    eventImageEntityDaoConfig = daoConfigMap.get(EventImageEntityDao.class).clone();
    eventImageEntityDaoConfig.initIdentityScope(type);

    userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
    historyEntityDao = new HistoryEntityDao(historyEntityDaoConfig, this);
    eventEntityDao = new EventEntityDao(eventEntityDaoConfig, this);
    eventImageEntityDao = new EventImageEntityDao(eventImageEntityDaoConfig, this);

    registerDao(UserEntity.class, userEntityDao);
    registerDao(HistoryEntity.class, historyEntityDao);
    registerDao(EventEntity.class, eventEntityDao);
    registerDao(EventImageEntity.class, eventImageEntityDao);
  }

  public void clear() {
    userEntityDaoConfig.getIdentityScope().clear();
    historyEntityDaoConfig.getIdentityScope().clear();
    eventEntityDaoConfig.getIdentityScope().clear();
    eventImageEntityDaoConfig.getIdentityScope().clear();
  }

  public UserEntityDao getUserEntityDao() {
    return userEntityDao;
  }

  public HistoryEntityDao getHistoryEntityDao() {
    return historyEntityDao;
  }

  public EventEntityDao getEventEntityDao() {
    return eventEntityDao;
  }

  public EventImageEntityDao getEventImageEntityDao() {
    return eventImageEntityDao;
  }
}
