package com.foodenak.itpscanner.persistence.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EVENT_IMAGE_ENTITY".
 */
public class EventImageEntity implements java.io.Serializable {

  private Long id;
  private String imageUrl;
  private Long eventId;

  // KEEP FIELDS - put your custom fields here
  // KEEP FIELDS END

  public EventImageEntity() {
  }

  public EventImageEntity(Long id) {
    this.id = id;
  }

  public EventImageEntity(Long id, String imageUrl, Long eventId) {
    this.id = id;
    this.imageUrl = imageUrl;
    this.eventId = eventId;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public Long getEventId() {
    return eventId;
  }

  public void setEventId(Long eventId) {
    this.eventId = eventId;
  }

  // KEEP METHODS - put your custom methods here
  // KEEP METHODS END
}
