package com.foodenak.itpscanner.persistence.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_ENTITY".
 */
public class UserEntity implements java.io.Serializable {

  private Long id;
  private String hashId;
  private String name;
  private String username;
  private String email;
  private Integer userPrivilegeId;
  private String accessToken;
  private java.util.Date redeemLuckydipAt;
  private java.util.Date redeemVoucherAt;
  private String imageUrl;

  // KEEP FIELDS - put your custom fields here
  // KEEP FIELDS END

  public UserEntity() {
  }

  public UserEntity(Long id) {
    this.id = id;
  }

  public UserEntity(Long id, String hashId, String name, String username, String email,
      Integer userPrivilegeId, String accessToken, java.util.Date redeemLuckydipAt,
      java.util.Date redeemVoucherAt, String imageUrl) {
    this.id = id;
    this.hashId = hashId;
    this.name = name;
    this.username = username;
    this.email = email;
    this.userPrivilegeId = userPrivilegeId;
    this.accessToken = accessToken;
    this.redeemLuckydipAt = redeemLuckydipAt;
    this.redeemVoucherAt = redeemVoucherAt;
    this.imageUrl = imageUrl;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getHashId() {
    return hashId;
  }

  public void setHashId(String hashId) {
    this.hashId = hashId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Integer getUserPrivilegeId() {
    return userPrivilegeId;
  }

  public void setUserPrivilegeId(Integer userPrivilegeId) {
    this.userPrivilegeId = userPrivilegeId;
  }

  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public java.util.Date getRedeemLuckydipAt() {
    return redeemLuckydipAt;
  }

  public void setRedeemLuckydipAt(java.util.Date redeemLuckydipAt) {
    this.redeemLuckydipAt = redeemLuckydipAt;
  }

  public java.util.Date getRedeemVoucherAt() {
    return redeemVoucherAt;
  }

  public void setRedeemVoucherAt(java.util.Date redeemVoucherAt) {
    this.redeemVoucherAt = redeemVoucherAt;
  }

  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  // KEEP METHODS - put your custom methods here
  // KEEP METHODS END
}
